import type { QuestionConfig } from './types';

export const DEFAULT_QUESTIONS: QuestionConfig[] = [
  {
    id: 'q-activities',
    field: 'activities',
    label: 'What activities are you doing?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'caving', label: 'Caving' },
      { value: 'climbing', label: 'Climbing' },
      { value: 'hiking', label: 'Hiking' },
      { value: 'sailing', label: 'Sailing' },
    ],
    parentId: null,
    order: 0,
  },
  {
    id: 'q-climbingType',
    field: 'climbingType',
    label: 'What type of climbing?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'trad', label: 'Trad' },
      { value: 'sport', label: 'Sport' },
      { value: 'bouldering', label: 'Bouldering' },
      { value: 'scrambling', label: 'Scrambling' },
    ],
    parentId: 'q-activities',
    order: 0,
    showWhen: { field: 'activities', includes: 'climbing' },
  },
  {
    id: 'q-cavingType',
    field: 'cavingType',
    label: 'What type of caving?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'srt_trip', label: 'SRT Trip' },
      { value: 'non_srt_trip', label: 'Non-SRT Trip' },
    ],
    parentId: 'q-activities',
    order: 1,
    showWhen: { field: 'activities', includes: 'caving' },
  },
  {
    id: 'q-weather',
    field: 'weather',
    label: 'What are the conditions like?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'cold', label: 'Cold' },
      { value: 'hot', label: 'Hot' },
      { value: 'rain', label: 'Rain' },
      { value: 'snow', label: 'Snow' },
    ],
    parentId: null,
    order: 1,
  },
  {
    id: 'q-duration',
    field: 'duration',
    label: 'How long is the trip?',
    selectMode: 'single',
    baseOptions: [
      { value: 'single_day', label: 'Single Day' },
      { value: 'multi_day', label: 'Multi Day' },
    ],
    parentId: null,
    order: 2,
  },
  {
    id: 'q-location',
    field: 'location',
    label: 'Home or abroad?',
    selectMode: 'single',
    baseOptions: [
      { value: 'home', label: 'Home' },
      { value: 'abroad', label: 'Abroad' },
    ],
    parentId: 'q-duration',
    order: 0,
    showWhen: { field: 'duration', notEquals: 'single_day' },
  },
  {
    id: 'q-shelter',
    field: 'shelter',
    label: 'Where are you sleeping?',
    selectMode: 'single',
    baseOptions: [
      { value: 'bothy', label: 'Bothy' },
      { value: 'hotel', label: 'Hotel' },
      { value: 'hut', label: 'Hut' },
      { value: 'tent', label: 'Tent' },
      { value: 'van', label: 'Van' },
    ],
    parentId: 'q-duration',
    order: 1,
    showWhen: { field: 'duration', notEquals: 'single_day' },
  },
  {
    id: 'q-sleepProvision',
    field: 'sleepProvision',
    label: 'What sleep provision is there?',
    selectMode: 'single',
    baseOptions: [
      { value: 'full_bedding', label: 'Full Bedding' },
      { value: 'mattress_only', label: 'Mattress Only' },
      { value: 'none', label: 'None' },
    ],
    parentId: 'q-shelter',
    order: 0,
    showWhen: { field: 'duration', notEquals: 'single_day' },
    autoWhen: { field: 'shelter', equals: 'hotel', setValue: 'full_bedding' },
  },
  {
    id: 'q-cooking',
    field: 'cooking',
    label: 'Cooking situation?',
    selectMode: 'single',
    baseOptions: [
      { value: 'none', label: 'None' },
      { value: 'provided', label: 'Provided' },
      { value: 'self_catered', label: 'Self Catered' },
    ],
    parentId: 'q-duration',
    order: 2,
    showWhen: { field: 'duration', notEquals: 'single_day' },
  },
];
