import type { QuestionConfig } from './types';

export const DEFAULT_QUESTIONS: QuestionConfig[] = [
  {
    id: 'q-activities',
    field: 'activities',
    label: 'What activities are you doing?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'hiking', label: 'Hiking' },
      { value: 'scrambling', label: 'Scrambling' },
      { value: 'climbing', label: 'Climbing' },
      { value: 'caving', label: 'Caving' },
      { value: 'sailing', label: 'Water Sports' },
      { value: 'snowsports', label: 'Snow Sports' },
    ],
    parentId: null,
    order: 0,
  },
  {
    id: '10cbb365-a7ca-478d-afd9-833e542e400f',
    field: 'Hiking (Weather)',
    label: 'Hiking in what weather?',
    selectMode: 'single',
    baseOptions: [
      { value: 'sunny', label: 'Sunny' },
      { value: 'mild', label: 'Mild' },
      { value: 'cold', label: 'Cold' },
    ],
    parentId: 'q-activities',
    order: 0,
    showWhen: { field: 'activities', includes: 'hiking' },
  },
  {
    id: 'e3f7f47f-bc3d-460b-87e9-a1e3c91e92dd',
    field: 'Scrambling grade',
    label: 'What kind of scrambling?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'grade_i', label: 'Grade I' },
      { value: 'grade_ii', label: 'Grade II' },
      { value: 'grade_iii', label: 'Grade III' },
    ],
    parentId: 'q-activities',
    order: 2,
    showWhen: { field: 'activities', includes: 'scrambling' },
  },
  {
    id: 'b93823fb-d7f3-4344-8d06-2190b8216040',
    field: 'Weather',
    label: 'In what weather?',
    selectMode: 'single',
    baseOptions: [
      { value: 'hot_sunny', label: 'Hot' },
      { value: 'mild', label: 'Mild' },
      { value: 'cold', label: 'Cold' },
    ],
    parentId: 'e3f7f47f-bc3d-460b-87e9-a1e3c91e92dd',
    order: 0,
  },
  {
    id: 'q-cavingType',
    field: 'cavingType',
    label: 'What type of caving?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'srt_trip', label: 'SRT Trip' },
      { value: 'non_srt_trip', label: 'Non-SRT Trip' },
    ],
    parentId: 'q-activities',
    order: 3,
    showWhen: { field: 'activities', includes: 'caving' },
  },
  {
    id: 'q-mmmjf7v3brews315',
    field: 'Conditions (Caving)',
    label: 'What kind of trip?',
    selectMode: 'single',
    baseOptions: [
      { value: 'involves_prolonged_submersion', label: 'Very wet' },
      { value: 'mostly_dry', label: 'Wet' },
      { value: 'dry', label: 'Dry' },
    ],
    parentId: 'q-cavingType',
    order: 0,
    showWhen: { field: 'cavingType', includes: '' },
  },
  {
    id: 'q-mmmjble2d429jjcc',
    field: 'Sailing Type',
    label: 'What type of WaterSports?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'dingy_sailing', label: 'Dingy Sailing' },
      { value: 'yacht_sailing', label: 'Yacht Sailing' },
      { value: 'surfing', label: 'Surfing' },
      { value: 'paddle_boarding', label: 'Paddle Boarding' },
      { value: 'wild_swimming', label: 'Wild Swimming' },
    ],
    parentId: 'q-activities',
    order: 4,
    showWhen: { field: 'activities', includes: 'sailing' },
  },
  {
    id: 'q-mmmjds6603m6ruim',
    field: 'Conditions (Sailing)',
    label: 'How colds the water?',
    selectMode: 'single',
    baseOptions: [
      { value: 'hot', label: 'Warm' },
      { value: 'cold', label: 'Cold' },
    ],
    parentId: 'q-mmmjble2d429jjcc',
    order: 0,
    showWhen: { field: 'Sailing Type' },
  },
  {
    id: 'q-climbingType',
    field: 'climbingType',
    label: 'What type of climbing?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'trad', label: 'Trad' },
      { value: 'sport', label: 'Sport' },
      { value: 'bouldering', label: 'Bouldering' },
    ],
    parentId: 'q-activities',
    order: 6,
    showWhen: { field: 'activities', includes: 'climbing' },
  },
  {
    id: 'q-weather',
    field: 'weather',
    label: 'In what weather?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'hot', label: 'Hot' },
      { value: 'mild', label: 'Mild' },
      { value: 'cold', label: 'Cold' },
    ],
    parentId: 'q-climbingType',
    order: 0,
    showWhen: { field: 'climbingType' },
  },
  {
    id: '4030858a-1614-4739-bbad-98a79dff8243',
    field: 'Snow Sports',
    label: 'What snow sports?',
    selectMode: 'multi',
    baseOptions: [
      { value: 'skiing', label: 'Skiing' },
      { value: 'snowboarding', label: 'Snowboarding' },
    ],
    parentId: 'q-activities',
    order: 7,
    showWhen: { field: 'activities', includes: 'snowsports' },
  },
];
